import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';

import '@/app/globals.css';
import NextAuthWrapped from "@/library/next.auth.wrapped";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QLNS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <NextAuthWrapped>
            {children}
          </NextAuthWrapped>
        </AntdRegistry>

      </body>
    </html>
  );
}
